// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXx3S9z9sIPPR9oprsWNoedJoPRLU_ofY',
    appId: '1:611949295104:web:056d32ebc6e21b466a0ae5',
    messagingSenderId: '611949295104',
    projectId: 'hotfocus-5411a',
    authDomain: 'hotfocus-5411a.firebaseapp.com',
    storageBucket: 'hotfocus-5411a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAejys3_5g3Hc3WhO-VGcgEloJ6Pplxe9U',
    appId: '1:611949295104:android:5df020a81634e68d6a0ae5',
    messagingSenderId: '611949295104',
    projectId: 'hotfocus-5411a',
    storageBucket: 'hotfocus-5411a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy-6hmnF6f6Ltvie3YCJjj0b1rLBEhbok',
    appId: '1:611949295104:ios:6cb5bdf81c205c6a6a0ae5',
    messagingSenderId: '611949295104',
    projectId: 'hotfocus-5411a',
    storageBucket: 'hotfocus-5411a.appspot.com',
    iosClientId: '611949295104-opvd16ses841ai3jij8g2ug7hhek5b5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotfocus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy-6hmnF6f6Ltvie3YCJjj0b1rLBEhbok',
    appId: '1:611949295104:ios:b516b4114a69a3b96a0ae5',
    messagingSenderId: '611949295104',
    projectId: 'hotfocus-5411a',
    storageBucket: 'hotfocus-5411a.appspot.com',
    iosClientId: '611949295104-fuo53813n2kgc5jh0ldl94nqafrttedg.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotfocus.RunnerTests',
  );
}
